BBS14/BBS14/urls.py
from django.conf.urls import url
from django.contrib import admin
from app01 import views

from django.views.static import serve
from BBS14 import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register/',views.register,name='reg'),
    url(r'^login/',views.login,name='login'),

    # 图片验证码相关操作
    url(r'^get_code/',views.get_code,name='gc'),

    # 首页
    url(r'^home/',views.home,name='home'),

    # 修改密码
    url(r'^set_password/',views.set_password,name='set_pwd'),

    # 退出登录
    url(r'^logout/',views.logout,name='logout'),

    # 暴露后端指定文件夹资源
    url(r'^media/(?P<path>.*)',serve,{'document_root':settings.MEDIA_ROOT}),

    # 点赞点踩
    url(r'^up_or_down/',views.up_or_down),

    # 评论
    url(r'^comment/',views.comment),

    # 后台管理
    url(r'^backend/',views.backend),

    # 添加文章
    url(r'^add/article/',views.add_article),

    # 编辑器上传图片接口
    url(r'^upload_image/',views.upload_image),

    # 修改用户头像
    url(r'^set/avatar/',views.set_avatar),

    # 个人站点页面搭建
    url(r'^(?P<username>\w+)/$',views.site,name='site'),

    # 侧边栏筛选功能
    # url(r'^(?P<username>\w+)/category/(\d+)/',views.site),
    # url(r'^(?P<username>\w+)/tag(\d+)/',views.site),
    # url(r'^(?P<username>\w+)/archive/(\w+)/',views.site),
    # 上面的三条url其实可以合并成一条
    url(r'^(?P<username>\w+)/(?P<condition>category|tag|archive)/(?P<param>.*)',views.site),

    # 文章详情页
    url(r'^(?P<username>\w+)/article/(?P<article_id>\d+)/',views.article_detail)
]

BBS14/app01/models.py
from django.db import models

# Create your models here.
'''
先写普通字段
之后再写外键字段
'''
from django.contrib.auth.models import AbstractUser

class UserInfo(AbstractUser):
    phone=models.BigIntegerField(verbose_name='手机号',null=True,blank=True)
    '''
    null=True  数据库该字段可以为空
    blank=True  admin后台管理该字段可以为空
    '''
    # 头像
    avatar=models.FileField(upload_to='avatar/',default='avatar/default.png',verbose_name='用户头像')
    '''
    给avatar字段传文件对象，该文件会自动存储到avatar文件下,然后avatar字段只保存文件路径avatar/default.png
    '''
    create_time=models.DateField(auto_now_add=True)

    blog=models.OneToOneField(to='Blog',null=True)

    class Meta:
        verbose_name_plural='用户表' # 修改admin后台管理默认的表名

    def __str__(self):
        return self.username


class Blog(models.Model):
    site_name=models.CharField(verbose_name='站点名称',max_length=32)
    site_title=models.CharField(verbose_name='站点标题',max_length=32)
    # 简单模拟，带你认识样式内部原理的操作
    site_theme=models.CharField(verbose_name='站点样式',max_length=64) # 存css/js的文件路径

    def __str__(self):
        return self.site_name

class Category(models.Model):
    name=models.CharField(verbose_name='文章分类',max_length=32)
    blog=models.ForeignKey(to='Blog',null=True)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name=models.CharField(verbose_name='文章标签',max_length=32)
    blog = models.ForeignKey(to='Blog', null=True)

    def __str__(self):
        return self.name


class Article(models.Model):
    title=models.CharField(verbose_name='文章标题',max_length=64)
    desc=models.CharField(verbose_name='文章简介',max_length=255)
    # 文章内容有很多，一般情况下都是使用TextField
    content=models.TextField(verbose_name='文章内容')
    create_time=models.DateField(auto_now_add=True)

    # 数据库字段设计优化
    up_num=models.BigIntegerField(verbose_name='点赞数',default=0)
    down_num=models.BigIntegerField(verbose_name='点踩数',default=0)
    comment_num=models.BigIntegerField(verbose_name='评论数',default=0)

    # 外键字段
    blog=models.ForeignKey(to='Blog',null=True)
    category=models.ForeignKey(to='Category',null=True)
    tags=models.ManyToManyField(to='Tag',
                                through='Article2Tag',
                                through_fields=('article','tag')
                                )
    def __str__(self):
        return self.title

class Article2Tag(models.Model):
    article=models.ForeignKey(to='Article')
    tag=models.ForeignKey(to='Tag')

class UpAndDown(models.Model):
    user=models.ForeignKey(to='UserInfo')
    article=models.ForeignKey(to='Article')
    is_up=models.BooleanField()  # 传布尔值  存0/1

class Comment(models.Model):
    user = models.ForeignKey(to='UserInfo')
    article = models.ForeignKey(to='Article')
    content=models.CharField(verbose_name='评论内容',max_length=255)
    comment_time=models.DateTimeField(verbose_name='评论时间',auto_now_add=True)
    # 自关联
    parent=models.ForeignKey(to='self',null=True) # 有些评论就是根评论

BBS14/templates/backend/add_article.html
<link rel="stylesheet" href="../../static/kindeditor/themes/default/default.css"/>
<script charset="utf-8" src="../../static/kindeditor/kindeditor-all.js"></script>
<script charset="utf-8" src="../../static/kindeditor/lang/zh-CN.js"></script>

<script type="text/javascript">
    var editor;
    KindEditor.ready(function (K) {
        editor = K.create('textarea[name="content"]', {
            //是否允许浏览服务器已上传文件,默认是false
            allowFileManager: true,
            uploadJson :'/upload_image/', // 上传图片的后端提交路径
            width:'100%',
            height:'600px',
            resizeType:1

        });
    });
</script>
{% extends 'backend/base.html' %}

{% block article %}
    <h3>添加文章</h3>
{#        直接利用form表单提交数据#}
    <form action="" method="post">
        {% csrf_token %}
        <p>标题</p>
        <div>
            <input type="text" name="title" class="form-control">
        </div>
        <p>内容</p>
        <div>
{#                        <textarea name="content" id="id_content" cols="30" rows="10"></textarea>#}
                        <textarea id="id_content" name="content" style="width:80%" rows="20"></textarea>

        </div>
        <p>分类</p>
        <div>
            {% for category in category_list %}
                <input type="radio" value="{{ category.pk }}" name="category">{{ category.name }}
            {% endfor %}

        </div>
        <p>标签</p>
        <div>
            {% for tag in tag_list %}
                <input type="checkbox" value="{{ tag.pk }}" name="tag">{{ tag.name }}
            {% endfor %}

        </div>
        <input type="submit" class="btn btn-danger">
    </form>
{% endblock %}

{#{% block js %}#}
{#    {% load static %}#}
{#    <script charset="utf-8" src="{% static 'kindeditor/kindeditor-all-min.js' %}"></script>#}
{#    <script>#}
{#        $(function () {#}
{#            KindEditor.ready(function(K) {#}
{#                window.editor = K.create('#id_content');#}
{#        });#}
{#        });#}
{##}
{##}
{##}
{#    </script>#}
{#{% endblock %}#}

<!-- 富文本编辑器 -->

{#<div class="form-group">#}
{#     <label>内容:</label>#}
{#     <textarea  name="content" type="text" class="form-control" >#}
{#     </textarea>#}
{#</div>#}

{#value="${(productInfo.productName)}"#}

BBS14/templates/backend/backend.html
{% extends 'backend/base.html' %}

{% block article %}
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>标题</th>
                <th>评论数</th>
                <th>点赞数</th>
                <th>操作</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for article in page_queryset %}
                <tr>
                    <td><a href="/{{ request.user.username }}/article/{{ article.pk }}/">{{ article.title }}</a></td>
                    <td>{{ article.comment_num }}</td>
                    <td>{{ article.up_num }}</td>
                    <td><a href="">编辑</a></td>
                    <td><a href="">删除</a></td>
                </tr>
            {% endfor %}

        </tbody>
    </table>
    <div class="pull-right">
        {{ page_obj.page_html|safe }}
    </div>
{% endblock %}

BBS14/templates/backend/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/home/">{{ request.user.blog.site_title }}</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">文章<span class="sr-only">(current)</span></a></li>
                <li><a href="#">随笔</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">更多<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="/{{ request.user.username}}/">{{ request.user.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">更多操作<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#" data-toggle="modal" data-target=".bs-example-modal-lg">修改密码</a></li>
                            <li><a href="/set/avatar/">修改头像</a></li>
                            <li><a href="/backend/">后台管理</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'logout' %}">退出登录</a></li>
                            </li>
                        </ul>
                        <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog"
                             aria-labelledby="myLargeModalLabel">
                            <div class="modal-dialog modal-lg" role="document">
                                <div class="modal-content">
                                    <div class="modal-content">
                                        <h1 class="text-center">修改密码</h1>
                                        <div class="row">
                                            <div class="col-md-8 col-md-offset-2">
                                                <div class="form-group">
                                                    <label for="">用户名</label>
                                                    <input type="text" disabled value="{{ request.user.username }}"
                                                           class="form-control">
                                                </div>
                                                <div class="form-group">
                                                    <label for="">旧密码</label>
                                                    <input type="password" id="id_old_password" class="form-control">
                                                </div>
                                                <div class="form-group">
                                                    <label for="">新密码</label>
                                                    <input type="password" id="id_new_password" class="form-control">
                                                </div>
                                                <div class="form-group">
                                                    <label for="">确认密码</label>
                                                    <input type="password" id="id_confirm_password"
                                                           class="form-control">
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-primary " data-dismiss="modal">
                                                        取消
                                                    </button>
                                                    <button class="btn btn-primary " id="id_edit">修改</button>
                                                    <span style="color: red" id="password_error"></span>
                                                </div>
                                                <br>
                                                <br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- /.navbar-collapse -->
                    </ul>
                {% else %}
                    <li><a href="{% url 'reg' %}">注册</a></li>
                    <li><a href="{% url 'login' %}">登录</a></li>
                {% endif %}


    </div><!-- /.container-fluid -->
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingOne">
                        <h4 class="panel-title">
                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne"
                               aria-expanded="true" aria-controls="collapseOne">
                                更多操作
                            </a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel"
                         aria-labelledby="headingOne">
                        <div class="panel-body">
                            <a href="/add/article/">添加文章</a>
                        </div>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel"
                         aria-labelledby="headingOne">
                        <div class="panel-body">
                            <a href="">添加随笔</a>
                        </div>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel"
                         aria-labelledby="headingOne">
                        <div class="panel-body">
                            <a href="">草稿箱</a>
                        </div>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel"
                         aria-labelledby="headingOne">
                        <div class="panel-body">
                            <a href="">其他</a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-md-10">

                <div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">文章</a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">随笔</a></li>
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">草稿</a></li>
    <li role="presentation"><a href="#file" aria-controls="file" role="tab" data-toggle="tab">文件</a></li>
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">设置</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home">
        {% block article %}

        {% endblock %}
    </div>
    <div role="tabpanel" class="tab-pane" id="profile">随笔页面</div>
    <div role="tabpanel" class="tab-pane" id="messages">草稿页面</div>
    <div role="tabpanel" class="tab-pane" id="file">文件页面</div>
    <div role="tabpanel" class="tab-pane" id="settings">设置页面</div>
  </div>

</div>


        </div>
    </div>
</div>
</body>
</html>